### ISSUE TITLE
Explicit tagging when deploying an image from dockerhub using the preflight tool

### ISSUE THREAD

**Issue by PingJamesB** [redhat-openshift-ecosystem/openshift-preflight#1088]
When using the preflight tool on an image in dockerhub it grabs all the tags associated with the manifest used. This is frustrating because for our images in dockerhub we use mutable tags that include latest or edge. But for the purpose of the openshift certified images we put in here: https://catalog.redhat.com/software/containers/pingidentity/pingaccess/64b1b09220a141da55489c33?architecture=amd64&image=651c5dd2b232df54f8bbe593
we would like just the immutable tags. For example just "309-7.3.1-redhat_ubi_ubi9-minimal_9.1-rl11".

Is there a way to do this? because the incorrectly mutable tags will confuse our customers and can be problematic in our deployment process.

**Comment by acornett21** [comment]
Hi @PingJamesB I'm not sure I understand the issue, preflight  uses the tag passed into the `check container` command and uses this to send data to our backend systems that are used by the catalog that you linked above. If I run preflight against the image you provided I get the below:

```
preflight check container docker.io/pingidentity/pingaccess:2309-7.3.1-redhat_ubi_ubi9-minimal_9.1-rl11
.
.
.
time="2023-10-25T13:15:49-07:00" level=info msg="This image's tag 2309-7.3.1-redhat_ubi_ubi9-minimal_9.1-rl11 will be paired with digest sha256:66fec85fe6919c287941a4cacbdab32629d32c9b0f0d01a8653586532299d795 once this image has been published in accordance with Red Hat Certification policy. You may then add or remove any supplemental tags through your Red Hat Connect portal as you see fit."
```

Then if you check the `cert-image.json` file that is on disk...the flag's section will be...
```
"tags": [
                {
                    "added_date": "2023-10-25T20:15:33Z",
                    "name": "2309-7.3.1-redhat_ubi_ubi9-minimal_9.1-rl11"
                }
            ]
```

This is what I also see in our backend systems as well for this tag. Can you please explain the issue you are seeing with specific log details? Thanks.

**Comment by PingJamesB** [comment]
I believe because I'm using a multi-arch manifest's tag not single image's tag there might be a difference but not sure. Below are two `check container` command's that ran 23 days ago. 
`preflight check container docker.io/pingidentity/pingaccess:7.3.0-redhat_ubi_ubi9-minimal_9.1-rl11-latest --submit --certification-project-id="${openshift_project_id}" --docker-config="${docker_config_dir}/config.json" --pyxis-api-token="${PYXIS_API_TOKEN}"
.
.
.
time="2023-10-02T21:50:40Z" level=info msg="This image's tag 7.3.0-redhat_ubi_ubi9-minimal_9.1-rl11-latest will be paired with digest sha256:<sha-value1> once this image has been published in accordance with Red Hat Certification policy. You may then add or remove any supplemental tags through your Red Hat Connect portal as you see fit."`

`preflight check container docker.io/pingidentity/pingaccess:7.3.0-redhat_ubi_ubi9-minimal_9.1-rl11-latest --submit --certification-project-id="${openshift_project_id}" --docker-config="${docker_config_dir}/config.json" --pyxis-api-token="${PYXIS_API_TOKEN}"
.
.
.
time="2023-10-02T21:51:48Z" level=info msg="This image's tag 2308-7.3.0-redhat_ubi_ubi9-minimal_9.1-rl11 will be paired with digest sha256:<sha-value2>once this image has been published in accordance with Red Hat Certification policy. You may then add or remove any supplemental tags through your Red Hat Connect portal as you see fit."`

Which resulted in the following error:
`Error: could not submit to pyxis: could not create rpm manifest: status code: 400: body: {"detail": "Image '{'published_date': datetime.datetime(2023, 9, 7, 19, 42, 45, 255000, tzinfo=<bson.tz_util.FixedOffset object at 0x7fef83679070>), 'registry': 'registry.connect.redhat.com', 'repository': 'pingidentity/pingaccess', 'push_date': datetime.datetime(2023, 9, 7, 19, 42, 45, 255000, tzinfo=<bson.tz_util.FixedOffset object at 0x7fef83679070>), 'tags': [{'name': '7.3.0-redhat_ubi_ubi9-minimal_9.1-rl11-latest', 'added_date': datetime.datetime(2023, 9, 7, 19, 42, 45, 255000, tzinfo=<bson.tz_util.FixedOffset object at 0x7fef83679070>)}, {'name': '2308-7.3.0-redhat_ubi_ubi9-minimal_9.1-rl11', 'added_date': datetime.datetime(2023, 9, 7, 19, 43, 0, 947000, tzinfo=<bson.tz_util.FixedOffset object at 0x7fef83679070>)}], 'published': True, 'tags#': 2}' is published, published image can't be updated.", "status": 400, "title": "Bad Request", "type": "about:blank", "trace_id": "0xc3f292408ef02c6ab485076c515831e9"}`
But the following three tags were applied to this manifest in the redhat registry `https://catalog.redhat.com/software/containers/pingidentity/pingaccess/64b1b09220a141da55489c33/history?0=a&1=m&2=d&3=6&4=4` :
[2309-7.3.1-redhat_ubi_ubi9-minimal_9.1-rl11](https://catalog.redhat.com/software/containers/pingidentity/pingaccess/64b1b09220a141da55489c33/?image=651c5dd2b232df54f8bbe593&architecture=amd64)
[7.3.1-redhat_ubi_ubi9-minimal_9.1-rl11-latest](https://catalog.redhat.com/software/containers/pingidentity/pingaccess/64b1b09220a141da55489c33/?image=651c5dd2b232df54f8bbe593&architecture=amd64)
[7.3.1-redhat_ubi_ubi9-minimal_9.1-rl11-edge](https://catalog.redhat.com/software/containers/pingidentity/pingaccess/64b1b09220a141da55489c33/?image=651c5dd2b232df54f8bbe593&architecture=amd64)

**Comment by PingJamesB** [comment]
It seems as though despite running preflight tool on a specific tag, we are somehow publishing multiple tags due to the underlying related sha256.

**Comment by acornett21** [comment]
Hi @PingJamesB The image in question isn't a multi-arch manifest image, it is just a single arch image....see below

```
crane manifest docker.io/pingidentity/pingaccess:2309-7.3.1-redhat_ubi_ubi9-minimal_9.1-rl11 
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1785,
         "digest": "sha256:66fec85fe6919c287941a4cacbdab32629d32c9b0f0d01a8653586532299d795",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

The reason you are getting the error `Error: could not submit to pyxis: ` is because once an image is published in our system it is `immutable`, meaning it's contents in our system can't be changed.

For the tags once the images is published we have a backend process that queries the registry for all tags for the given sha that was just published and [syncs](https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.69/html/red_hat_software_certification_workflow_guide/assembly_configuring-the-container-project_openshift-sw-cert-workflow-working-with-containers#proc_viewing-the-image-test-results_openshift-sw-cert-workflow-complete-pre-certification-checklist-for-containers) them. This is so partners do not have to manage tags in two places, their registry and our catalog. Tags are neither `mutable` or `immutable` they are just a metadata property that can be moved by convention and not an intrinsic value of the OCI image. The only immutable property of an image in an OCI registry is the sha.

If you only want one tag in our catalog, then the certified digest should only contain the one tag. Also, if you are build an operator/helm chart to also certify with your project, tags are not allowed, only `sha's` digests are allowed in CSVs/etc.

Since this isn't an issue with preflight, I'm going to close this issue. If you need further help, feel free to open a [support case](https://access.redhat.com/articles/38363).

**Comment by PingJamesB** [comment]
Just to clarify, there is a backend process which queries the source registry for all the tags associated with the sha that the given tag is associated to(I am not providing the sha directly, but instead the specific tag I want to grab). Additionally, there is no way to configure the tool to not sync the tags associated  and instead just use the tag given? Because in our dockerhub  registry that is the source here, we have tags that include edge and latest, so our customers no what is the latest and greatest etc. These are then rotated to the next iteration once new images are deployed, but this is not the case for our tags in the OCI registry, which we synced initially but are not continually synced and can not be overridden.

**Comment by acornett21** [comment]
@PingJamesB Yes, that is correct there is a backend process that syncs tags, so we can effectively serve content from `registry.connect.redhat.com` when partners choose for Red Hat to proxy to their registry. No, there is not a way to turn this off, otherwise we could not proxy content, since we would not know what is and is not certified. You can manually trigger this `sync` process in the Connect UI anytime you wish (this is in the document I linked yesterday), I triggered this process and now there are only two tags listed in the catalog.

As mentioned yesterday, if you need more help, it would better to talk specifics in a support case.
