### ISSUE TITLE
KONFLUX-5392: Possibly inefficient memory usage when checking container

### ISSUE THREAD

**Issue by jhutar** [redhat-openshift-ecosystem/openshift-preflight#1214]
## Bug Description
Hello. In Konflux this container can consume lots of memory: https://github.com/konflux-ci/build-definitions/blob/54b1217b28328ffbf4ad9cd1c3681b8b37449fe1/task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml#L23-L35

E.g. in case of https://github.com/openshift/lightspeed-service repo, memory consumption spikes above 8 GiB:

![image](https://github.com/user-attachments/assets/a2b93660-9f9b-4933-a0b0-b81ac77db25d)

## Version and Command Invocation
`quay.io/opdev/preflight:stable@sha256:e4707e5f3a61c737c9b5f04d2ebe45675fde2d1c72b65df9152e8a053acd6c61`

## Steps to Reproduce:
1) In Konflux Prod cluster Prometheus check query like this:
```
(
    avg by (namespace, pod) (
        container_memory_working_set_bytes{container=~".*check-container.*"}
    )
    -
    avg by (namespace,  pod) (
        kube_pod_container_resource_requests{container=~".*check-container.*"}
    )
) > 0
```

## Expected Result
Task should not be using too much memory

## Actual Result
On some repos task uses lots of memory

**Comment by bcrochet** [comment]
I've run multiple tests, and I don't see the memory usage getting above ~60MB.

Are you sure that `container_memory_working_set_bytes` is the metric you want? That metric includes cache, which is not something that preflight would directly control.

I can't get a larger version of the above graph (getting 404) so I can't see exactly what it is that you are seeing.

**Comment by jhutar** [comment]
Oh my, thank you Brad. You are right. I need to be using `container_memory_rss` for this metric which looks perfectly OK. I reported this when I was looking at actual memory usage during build where `container_memory_working_set_bytes` makes sense. Sorry for mess!

**Comment by bcrochet** [comment]
I've done some more instrumenting of code, and I stand by my previous comment. I'm just not seeing an actual allocation by preflight that gets anywhere near what your graph implies. Because the metric you are using includes cache, that's just not anything that preflight can control. 

I'll upload the log from my latest run that shows memory allocation at various points within a preflight run. The values that are useful are the Alloc and Sys values. Descriptions of those values are [here](https://pkg.go.dev/runtime#MemStats) .
[preflight.log](https://github.com/user-attachments/files/17870300/preflight.log)

**Comment by bcrochet** [comment]
> Oh my, thank you Brad. You are right. I need to be using `container_memory_rss` for this metric which looks perfectly OK. I reported this when I was looking at actual memory usage during build where `container_memory_working_set_bytes` makes sense. Sorry for mess!

Glad you got it sorted. Closing.
