### ISSUE TITLE
Extend Podman interfaces to allow mounting an image instead of a container in unshare-based checks.

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#137]
## Is your feature request related to a problem? Please describe.
Yes, when running checks for operator bundles, which are non-runnable container, I must fake-create the container in order to extract the bundle and perform my check.

Example: #124

## Describe the solution you'd like.
Instead, it would be ideal if we could mount the container image without running the container at all.

#126 implemented similar functionality for containers. A PR resolving this issue would have to expand on that, allowing for "running in a filesystem" to work for either containers or images. 

This would likely mean expanding the podmanEngine interface to allow for mounting an image.

## Describe alternatives you've considered.
The alternative is implemented in #124 as an example, and described above in the related problem description. We must create the container to extract resources from that filesystem, and then we must clean up after ourselves.

**Comment by bcrochet** [comment]
I've already commented on the PR, but thought I should also put it here for easier discussion.

Is there a reason to keep the container mounting around? What use case is the container mount necessary rather than just the image mount. TBH, I would have just implemented it with the image mount had I realized it could be done with podman instaed of requiring buildah.
