### ISSUE TITLE
Improve BasedOnUBI check to ensure reliable validation of UBI vs. RHEL images

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#25]
The BasedOnUBi check currently checks to ensure that the `/etc/os-release` file contains the following keys:

```
ID="rhel"
NAME="Red Hat Enterprise Linux"
```

Technically, this passes with RHEL images:

```
podman run \
    -it --rm \
    --entrypoint cat \
    registry.access.redhat.com/rhel7@sha256:d7de4fd7b3850d03d2d432a3dce209e99db31d6a4a3d0017a195363208ade4f5 \
    /etc/os-release \
    -- | egrep "^ID=|^NAME="

NAME="Red Hat Enterprise Linux Server"
ID="rhel"
```

We'll need to decide:
* Should we be more explicit in identifying something is UBI, and how we do that, or if we want to pass RHEL-based images
* How we identify that something is specifically UBI and not RHEL

If we want to be more specific with this check, we'll need to
* Update `certification/internal/shell/based_on_ubi.go` to factor in the additional validation
* Update `certification/internal/shell/based_on_ubi_test.go` to test that validation

**Comment by tonytcampbell** [comment]
Good catch.  Let me check with the folks defining the policy to confirm if RHEL images should pass this check as well.

**Comment by bcrochet** [comment]
PR #2 introduces an InspectImage to the the podmanEngine. This could be useful... Perhaps labels on the base image?

**Comment by komish** [comment]
@bcrochet Possibly, but we'd have to go reach out to UBI folks and have them do so all the way at the UBI build. And it would cause old builds to fail.

**Comment by bcrochet** [comment]
> @bcrochet Possibly, but we'd have to go reach out to UBI folks and have them do so all the way at the UBI build. And it would cause old builds to fail.

I'm pretty sure it already has the labels. Take a look at 'podman image inspect registry.access.redhat.com/ubi8/ubi'

**Comment by komish** [comment]
@tonytcampbell where did we land on this?

**Comment by skattoju** [comment]
seems like the ubi check was removed from the ansible checks according to https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/pull/31

**Comment by komish** [comment]
Hey @skattoju do you happen to know where we landed on this? Can it be closed?

**Comment by skattoju** [comment]
We said we will just check tags and /etc/os-release for now and add the
layer checking later but I believe this is still needed.

**Comment by jomkz** [comment]
Bringing this issue back to the forefront. We need to address #375 as part of the container certification work so I am wondering if we can address both of them together.

**Comment by bcrochet** [comment]
I have a clearer picture from the CVP codebase on how to accomplish this in a consistent and useful manner.

**Comment by jfrancin** [comment]
Please note that for RHEL-7, there is both a supported UBI and a RHEL base image - both of which are perfectly valid for use in partner-generated containers. 

RHEL-7 supported images in Comet:

https://comet.engineering.redhat.com/containers/repositories/57ea8cdc9c624c035f96f344 (rhel7/rhel)
https://comet.engineering.redhat.com/containers/repositories/58b9d66f4b339a07cca5359e (rhel7/rhel-atomic)

**Comment by skattoju** [comment]
This check should do what the CVP implementation does i.e. do a call to pyxis with SHAs of the image under test to see if there is a match to the uncompressed top layer SHA of ubi images or with an existing certified image which should also be based on ubi.[1]

However the above pyxis call is fairly expensive and always times out in prod when made from outside via a load balancer as the load balancer always drops the connection and pyxis team does not have control over this. It works in CVP has the call is direct and does not get dropped despite taking a long time.

In order to support this there is an effort to refactor the query used by pyxis to get SHAs[2]

[1]https://gitlab.cee.redhat.com/cvp/pipeline/-/blob/master/src/org/cvp/pipeline/IsvContainerUtils.groovy#L17
[2]https://issues.redhat.com/browse/ISV-1843
