### ISSUE TITLE
[Container Cert] Container cannot modify content provided by Red Hat

### ISSUE THREAD

**Issue by tonytcampbell** [redhat-openshift-ecosystem/openshift-preflight#425]
Container image cannot modify content provided by Red Hat packages or layers, except for files that are meant to be modified by end users, such as configuration files

**Comment by bcrochet** [comment]
The CVP check used rpm -V in order to satisfy this requirement. We have at least two options here:

1. Use the 'rpm' command from the host, against the exported FS from the image. Con here is that the host may not be an RPM-based Linux. Or even Linux for that matter.
2. Export the layers into the filesystem (or at least the filenames) one at a time in order to capture the list of files, and then verify that subsequent layers do not modify the Red Hat base layer.

I think 2 is probably the better pursuit to start.
