### ISSUE TITLE
has_unique_tag policy is not compatible with image stored in a private registry

### ISSUE THREAD

**Issue by pierreblanc** [redhat-openshift-ecosystem/openshift-preflight#454]
## Bug Description

I would like to release my operator only when it will be certified, so I am doing the pre-flight tests with private registry.

Unfortunately the policy has_unique_tag failed in this scenario.

## Version and Command Invocation

Version : quay.io/opdev/preflight:1.1.0-alpha2

> time="2022-03-03T18:03:53Z" level=info msg="check completed: HasUniqueTag" ERROR="GET https://index.docker.io/v2/library/jumphost.xxxx.xxx.xxx/tags/list?n=1000: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/jumphost.xxxx.xxx.xxx/ Type:repository]]" result="GET https://index.docker.io/v2/library/jumphost.xxxx.xxx.xxx/tags/list?n=1000: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/jumphost.xxxx.xxx.xxx Type:repository]]"

## Steps to Reproduce:
preflight check container jumphost.xxxx.xxx.xxx:5000/my_operator:v2.1.1

**Comment by acornett21** [comment]
@pierreblanc Thanks for creating an issue. This issue is due to how the registry is configured and not allowing request to `/tags/list` endpoint then an issue with this check itself. 

If you run `crane ls <registry/repo/image>` or `skopeo inspect docker://<registry/repo/image:tag> --debug` you should get the same `401` error for the `tags/list` route.

With that said we are talking about this check specifically and will reply back once we know more. Hope that info helps. Let us know if you have any more questions.

**Comment by acornett21** [comment]
@pierreblanc We looked further and it seems that `crane` the tool we are using, uses different `options` for `pull` vs `list` we will have a fix for this in the next day or so.

**Comment by acornett21** [comment]
There isn't an issue with `preflights` implementation of `crane.ListTags` from an authorization prospective (ie username/password) for registries with authentication. Crane takes care of using the `DefaultKeychain` on the system for `ListTags` just like it does for `Pull`. 

The main issue that was causing this was that `preflight` was doing custom parsing of the URI, and not taking into account the possibility of `port` numbers being supplied. The port issue was fixed as a part of issue #467.
