### ISSUE TITLE
Proposal - Make pyxis credentials optional unless submitting

### ISSUE THREAD

**Issue by bcrochet** [redhat-openshift-ecosystem/openshift-preflight#552]
# Proposal - Make Pyxis credentials optional unless Submitting

## Current State

The current state of `preflight check container` requires a user to provide Pyxis credentials, via the `--certification-project-id` and `--pyxis-api-token`. This requires that a project be set up in Pyxis prior to utilizing the preflight tool.

The reason for these credentials is that a call to Pyxis is required to get the project information, and from that project info, check the `OsContentType` field. If it is set to 'scratch', then a subset of container checks are run. Currently, that means three checks are not performed:

* BasedOnUBI
* HasModifiedFiles
* HasNoProhibitedPackages

## Proposal

In order to make the UX for the vast majority of containers simpler and easier, it is being proposed to make the above credentials optional, and only checking for a scratch image when those are provided. They would become required should the `--submit` flag also be given.

The flow would become:

* Check if credentials are provided.
* If not, run all checks
* If they are, check for scratch, and act accordingly.

This could mean that if a container is indeed being based on scratch, without credentials, the three checks mentioned above will not pass. So, a partner using a scratch image has two options:

1. Pass the credentials, with a project set OsContentType: scratch, and have the same experience as on submit.
2. Don't pass credentials, knowing that the experience upon submit will differ (but only in that certain checks will NOT be run)

The positive of this change would be that the experience for a non-scratch (again, likely the vast majority of containers), would result in an easier experience, as the lack of credentials would not change the experience of running checks, both with and without `--submit`.

### Other necessary changes

Additional information should be added to the three checks that shouldn't be run on a scratch image to indicate as such, and that if they are attempted against a scratch image, they are expected to fail.

**Comment by komish** [comment]
For context, I believe this relates to https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/549.

**Comment by komish** [comment]
> Making the parameters optional together with the scratch option, makes the above assumption incorrect.

To clarify, are you specifically referring to the fact that we remove checks for scratch images? Because success/failure should be identical otherwise, regardless of the value of the submit flag.

**Comment by itroyano** [comment]
> To clarify, are you specifically referring to the fact that we remove checks for scratch images? Because success/failure should be identical otherwise, regardless of the value of the submit flag.

One specific user-unfriendly case of the above equation, is a user running his X image twice -
- first time G is skipped (without necessarily the user knowing it should run), resulting in a successful flow.
- second time, with submit, G is executed and G(X)=fail, resulting in a failed flow.   note: failed flow because of a check.  not because something went wrong with the submit action itself.

From the user's point of view, this can be a frustrating experience, and may present Preflight as an unreliable or inconsistent tool.

**Comment by komish** [comment]
Understood. I generally agree. I think the difference in scenario is that running without the `--submit` flag will almost always result in _more check_ given @bcrochet's current design. In other words, I believe the design currently enforces that running without `--submit` prevents Preflight from determining whether or not your image is allowed to be based on scratch (because that requires API calls). That means we would run the standard container policy (more checks), not the scratch policy. 

Unless I'm understanding incorrectly, the result of that should be that we don't encounter the user-unfriendly path that you describe. Instead, we encounter the slightly less user-unfriendly path which is that users of scratch images fail extra checks if they decide to run without providing credentials, and the certification submission workflow (e.g. when the user provides full credentials) would relax the requirements.

@bcrochet make sure I captured that correctly.

**Comment by bcrochet** [comment]
> One specific user-unfriendly case of the above equation, is a user running his X image twice -
> 
>     * first time G is skipped (without necessarily the user knowing it should run), resulting in a successful flow.
> 
>     * second time, with submit, G is executed and G(X)=fail, resulting in a failed flow.   note: failed flow because of a check.  not because something went wrong with the submit action itself.

That is not how it would work. The only workflow that this would change would be a scratch one. And in the case of scratch, if run without credentials, they would run all the checks.

If the run with credentials, OR they go to submit, they will run fewer checks, not more. Your scenario is not possible.

> And yes, it all boils down to the `isScratch` check. while we can document a requirement as @bcrochet mentioned above, that a scratch user must provide all flags - we cannot enforce it.

The reason being, Pyxis is the source of truth as to whether a container image is even *allowed* to skip those three checks. This is why we don't have a --scratch flag that can be passed. So a project marked as scratch needs to provide credentials if they want to suppress those checks before submitting, or just know that those three checks will fail until they do.

Since scratch is not going to be extremely prevalent. to me, this is a small trade-off for a better UX for most projects.

**Comment by bcrochet** [comment]
> Understood. We should document this, for the scratch users that come complaining about a failed `BasedOnUbi`, and make sure whoever is troubleshooting such an issue knows to ask about scratch first. do we have a `troubleshooting.md` ?

Not sure about troubleshooting.md, but an FAQ would not be a bad place for something like this.

**Comment by skattoju** [comment]
I think this approach makes sense. The only thing that feels awkward (from the implementation perspective but not the UX perspective) is us skipping tests based on something pyxis knows i.e. the scratch status. Probably unpopular opinion but I think in case of scratch images we should still do those tests and submit failed results and let pyxis decide whether to move forward with them since it's the one that knows about the from scratch exceptions

**Comment by jomkz** [comment]
I agree with @skattoju, I feel like we are building exceptions into preflight and from there where does it stop as we add more policies? If Pyxis is the source of truth or authority for certification then we should just submit the failed results and let the exception be granted through a support interaction.

**Comment by acornett21** [comment]
> I agree with @skattoju, I feel like we are building exceptions into preflight and from there where does it stop as we add more policies? If Pyxis is the source of truth or authority for certification then we should just submit the failed results and let the exception be granted through a support interaction.

@jomkz  I feel this is the direction that `preflight` should go, but I believe that the business wants to drive `preflight` in another direction. IE we are the source of truth and we run x,y,z,1,4,7 checks based on what is setup in pyxis when a project is created and exceptions have been added. (However, I'm not certain that exception will be added before hand, since today they are done after the fact. We should get clarity from the business if they are going to be doing exceptions upfront or not.) 

I feel like if we change this UX experience now, and then have to add back in those arguments later and make them required for a `none submit` flow, then that leaves us in a worse UX shape than we are in today. Say an exception comes for `RunningAsRoot` (which I foresee happening) or any other check? Do we do the same thing then, run all the checks, fail, then only pass on submit? How does a user know what really will pass and what really will fail if they are supposed to use this tool in an iterative fashion. To me that seems like a terrible UX and worse than requiring flags from the get go.

I realize I'm in the minority here, I'm just trying to protect our future interests. Ideally pyxis should be the source of truth and we should not worry about these issues, maybe we can push for that.

**Comment by acornett21** [comment]
> Not sure about troubleshooting.md, but an FAQ would not be a bad place for something like this.

I think the troubleshooting.md would be [here](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/containers/troubleshooting.md) like it is for `check operator` flow. And we could build out this documentation.

**Comment by komish** [comment]
>  (_@skattoju_)
> I think this approach makes sense. The only thing that feels awkward (at least from the implementation perspective may be not the UX perspective) is us skipping tests based on something Pyxis knows i.e. the scratch status. Probably unpopular opinion but I think in case of scratch images we should still do those tests and submit failed results and let Pyxis decide whether to move forward with them since it's the one that knows about the from scratch exceptions

---

> (_@jomkz_)
> I agree with @skattoju, I feel like we are building exceptions into preflight and from there where does it stop as we add more policies? If Pyxis is the source of truth or authority for certification then we should just submit the failed results and let the exception be granted through a support interaction. 

I generally agree with this point of view. I see UX problems introduced here as follows:

1) The pipelines running Preflight need to know if this is going to change how they evaluate results. I believe they check the overall state of our User Response. If they need to handle exceptions, they need to know about this before we implement it, unless it doesn't affect operator certification.

2) Users will need to know what things they can safely ignore due to the exceptions they have associated with their Pyxis projects. If I'm a developer working on my container, and I see failures, my instinct is going to be to figure out why - not whether I can safely ignore the failure.

FWIW, I think these UX problems are a good compromise versus requiring a ton of flags and preparatory interactions with Connect in order to just run the tests locally and see if my asset _might_ pass.

As I'm understanding this change, it sounds like we could also drop the Scratch container policy altogether.

---

> (_@acornett21_)
> ...
> ... I feel this is the direction that preflight should go, but I believe that the business wants to drive preflight in another direction...
> ...we are the source of truth and we run x,y,z,1,4,7 checks based on what is setup in pyxis when a project is created and exceptions have been added.
> ...

@acornett21 I see this point of view manifesting in the operator certification pipeline(s), where Preflight is the tool being executed to identify whether the asset should pass.

I mentioned this already once, but what we're trying to serve is two differing use cases. One is as the tool to test your asset so that you can increase the likelihood that you pass certification (call this use case A), and the other is the certification verification (use case B).

These have slightly different requirements. For (B), we are perfectly okay setting expectations that we need to pull real-time state of your project, metadata, exceptions, etc. from Pyxis. For (A), I feel like we should be reducing friction (which is what @bcrochet's proposal is about). I would say right now, we mostly serve (B). A user looking to serve (A) can still do so, but with extra friction because we mostly serve (B).

I'll refrain from detailing my far-future view on having separate subcommands that are certification oriented vs. testing oriented (pulling from the same policies) for a future proposal 😸

**Comment by bcrochet** [comment]
> I feel like if we change this UX experience now, and then have to add back in those arguments later and make them required for a `none submit` flow, then that leaves us in a worse UX shape than we are in today. Say an exception comes for `RunningAsRoot` (which I foresee happening) or any other check? Do we do the same thing then, run all the checks, fail, then only pass on submit? How does a user know what really will pass and what really will fail if they are supposed to use this tool in an iterative fashion. To me that seems like a terrible UX and worse than requiring flags from the get go.

The arguments aren't going away. They would just become optional for non-submit. RunAsRoot is a different scenario as well. That information doesn't come from Pyxis. Scratch is determined exclusively from Pyxis.

As to knowing what passes/fails etc. Take the RunsAsRoot example... A partner would *know* that the check won't pass, because they asked for an exception. They aren't going to be confused by that.

**Comment by bcrochet** [comment]
>     1. The pipelines running Preflight need to know if this is going to change how they evaluate results. I believe they check the overall state of our User Response. If they need to handle exceptions, they need to know about this before we implement it, unless it doesn't affect operator certification.

I think we can, upon submit, also massage the result if needed. Get some data from pyxis then, determine if it is scratch, and remove the 3 checks at that time from the result, and if what's left is passing, then set Pass: True. So instead of worrying about scratch up-front, we move the processing to a later step in the preflight execution.

>     2. Users will need to know what things they can safely ignore due to the exceptions they have associated with their Pyxis projects. If I'm a developer working on my container, and I see failures, my instinct is going to be to figure out why - not whether I can safely ignore the failure.

My thinking is that if they know enough that they want/need an exception, they will know what they can safely ignore as failures in preflight checks.

**Comment by acornett21** [comment]
> The arguments aren't going away. They would just become optional for non-submit. RunAsRoot is a different scenario as well. That information doesn't come from Pyxis. Scratch is determined exclusively from Pyxis.
> 
> As to knowing what passes/fails etc. Take the RunsAsRoot example... A partner would _know_ that the check won't pass, because they asked for an exception. They aren't going to be confused by that.

I'm saying `RunsAsRoot` or any other check could be the _same_ scenario as Scratch where the business asks us to source the data from pyxis and run that check based on a flag stored in pyxis. I'm thinking the business only wants `Success` cases to end up in pyxis and all exception handling/processing done upfront in `preflight` and not offloaded to pyxis, that's why I bring up another use-case that was mentioned this week as well.

So in your example, sure they might know it won't pass, but they would expect that check to not even run while they are iterating on their container, since they have asked for an exception. And then be frustrated why there exception wasn't granted.

**Comment by bcrochet** [comment]
That sounds like a communication problem, not a software problem. And I think we can also do that checking/filtering at submit time.

**Comment by acornett21** [comment]
> That sounds like a communication problem, not a software problem. And I think we can also do that checking/filtering at submit time.

It's totally a software problem, it's a software usability, user experience issue. If users will only know what tests will truly pass during submission time that's a bad user experience.

**Comment by bcrochet** [comment]
> It's totally a software problem, it's a software usability, user experience issue. If users will only know what tests will truly pass during submission time that's a bad user experience.

The tests that pass won't change. You just won't have the failing ones.

We have Suggestion field in the output. We put in there "If this is a scratch image, and you have an exception, this test is not expected to pass, and will not be a part of the submission to Red Hat".

**Comment by acornett21** [comment]
> The tests that pass won't change. You just won't have the failing ones.
> 
> We have Suggestion field in the output. We put in there "If this is a scratch image, and you have an exception, this test is not expected to pass, and will not be a part of the submission to Red Hat".

Yes, I know that passing tests won't change. I probably should have said "If users only know what tests will be run during submission time that's a bad user experience". IE having different tests for `submit` vs `non submit`. 

I'm trying to explain other use cases other than scratch as well, but it seems future cases seem not to matter in this discussion, which is fine. If we want to deal with those cases when they are asked for, and then have to call pyxis upfront for those cases, and then deal with UX fall-out then, so be it.

**Comment by bcrochet** [comment]
Possible alternative. Again, would be a documentation and communication problem. We make this part optional as proposed. However, we make it very clear that if you are seeking an exception of any kind, you will need to have a project ID and token. Basically, when the exception is requested, it is communicated that in order to have the correct set of tests they have to run always with these flags.

**Comment by tkrishtop** [comment]
Hi @bcrochet it would be nice to have things done as you propose. 

When we work with partners, some of them are determined to be certified but the others are not sure. Usually, we would do a presentation and then the next request is to run the tests fast to get an overview. The partners would like to first estimate an upcoming work by checking test results, and then commit by dealing with connect.redhat.com, creating accounts, etc.

**Comment by bcrochet** [comment]
We seem to have enough of a consensus on this to move forward. Will implement this as a fix to #549.
