### ISSUE TITLE
First Usage - Impressions and issues

### ISSUE THREAD

**Issue by DanArlowski** [redhat-openshift-ecosystem/openshift-preflight#584]
## Our RH Certification Status
we at Sosivio currently Working on certifying our product & operator for Red Hat Openshift.
Requirements are pretty straightforward from the documentation, so preflight came "just in time" to check our containers pre-publish and pre-releasing the frist version to be certified.

## How we're Preflight
- We use preflight to check out test containers
- We using a script to run preflight on our container list

## Our Plan to use Preflight
- we plan to submit the release images to be signed and verified automatically 
- our main goal is to not use the Red Hat Partner program **AT ALL** including creating new containers, archiving existing, creating new releases. we'll only use the UI to update text based field (I.e - customer facing descriptions, etc)

## Problems encountered while using Preflight
1. We have a Privileged containers - their tests fail, So this is a high priority feature for us, and we won't be able to use preflight completely without that.
2. We have scratch containers, we know that currently you need to open a support case in order to make the mark the container as scratch, we'll be glad to see that automatically, as evaluation a scratch contaiiner should be rather easy. (That is less Preflight oriented.)
3. submitting the images does not show on The Partner portal - I guess thats because its still in beta and gets manual approval by Red Hat
4. We'll really want to see a `--override` flag - so we'll override exsting image - that is mostly useful in testing
5. We'll like to see in preflight some more API Calls - like creating/archiving projects
6. We'll like to see a `--publish` flag, to publish the tag after submmiting, if the test pass.

 ## Overall impression
We feel this tool may be very useful for us to continuously certify Sosivio

**Comment by acornett21** [comment]
@DanArlowski Thanks for the detailed feedback! Few comments below. 

> ## Problems encountered while using Preflight
> 1. We have a Privileged containers - their tests fail, So this is a high priority feature for us, and we won't be able to use preflight completely without that.

When you say `privileged` do you mean your containers need to run as root? If so in you project settings in `Connect` you can change the `Host Level access` to `Privileged`. When you go to `--submit` the `RunAsNonRoot` check will not run, and will not be in the `Test Results` 

> 2. We have scratch containers, we know that currently you need to open a support case in order to make the mark the container as scratch, we'll be glad to see that automatically, as evaluation a scratch contaiiner should be rather easy. (That is less Preflight oriented.)

I don't foresee this exception process changing right now, but maybe it will evolve overtime to be more streamlined. But even still it would live outside of this tool.

> 3. submitting the images does not show on The Partner portal - I guess thats because its still in beta and gets manual approval by Red Hat

Where in the `Partner portal` does the image not appear? `preflight` gives links to both `/scan-results` and `/overview` where you can see the image. 

> 4. We'll really want to see a `--override` flag - so we'll override exsting image - that is mostly useful in testing

Can you explain what this means? Or the use-case? You are able to submit n number of `sha`s for the same container project and the last test results would be used,  and then if `preflight` test's passed as well as other tests that run after this tool, the image could be published.

> 5. We'll like to see in preflight some more API Calls - like creating/archiving projects

`preflight` is a tool for running `checks` for various certifications, I don't foresee it as also being a tool to manage projects in connect.

> 6. We'll like to see a `--publish` flag, to publish the tag after submmiting, if the test pass.

Since `preflight` is just one tool in the entire `certification` process, ie the `preflight` checks, and other process run to check other attributes of the container ie security vulnerabilities for example, I'm not sure we would implement a flag to auto publish, but definitely something we can discuss with other systems involved in the certification process.

**Comment by komish** [comment]
Just doing some tidying up of our issues, and from what I can see in the original action items, I believe the top 3 have been addressed, 4 needs more clarity, 5 and 6 are a bit out of scope today. With all of that said, this issue has been open for some time, and the tooling has changed a bit since its initial creation.

Within the context of this issue, I think we can mark this closed.
We'd love to have you test again and provide any new feedback you may have.
Thank you for submitting this issue!

**Comment by DanArlowski** [comment]
@komish  - I understood from you comment that no 2. is addressed - is it possible to verify scratch based container without opening a support case?

**Comment by komish** [comment]
Hey @DanArlowski! So, when you provide Preflight your credentials, it automatically reaches into your Project via public APIs and looks for the exception setting indicating that you've been approved to use a scratch image for that project.

Preflight then automatically applies a modified policy specifically for scratch images, which bypasses UBI checks. This policy is only ever applied to images that have this flag, so you will need to provide your Pyxis API Token and Project ID for this to work.

Re-reading your second item, I realized I missed that you desire to automatically detect that the image is built from scratch, and set your project flag accordingly, resulting in the above-mentioned policy.

I believe the issue there is that building from scratch, today, requires a manual exception from Red Hat, which motivates the support ticket. As you mention, that particular piece, today, is less preflight oriented, so while we might be able to detect the use of scratch reliably, we wouldn't be able to grant you the exception through preflight.

Hope that helps!
