### ISSUE TITLE
Preflight does not detect the modification of the package and throw the warning or error in the results

### ISSUE THREAD

**Issue by jinhli** [redhat-openshift-ecosystem/openshift-preflight#846]
## Bug Description
Infinidat certified an openstack image, they replaced a file via the command line  for this package python3-requests-2.20.0-2.1.el8_1.noarch in their  [dockerfile](https://github.com/Infinidat/cinder/commit/dc044c87791fb9d7caed7658d0cdd15d4520286c#diff-e58f4ed034f19f0d4c01795b2255eb8860f9a9bf478f90d4bb18e58d832197f8)
here is the command line :
 RUN curl -Ls [ https://raw.githubusercontent.com/psf/requests/v2.20.0/requests/__init__.py|https://raw.githubusercontent.com/psf/requests/v2.20.0/requests/_init.py] > /usr/lib/python3.6/site-packages/requests/init_.py

Whent they ran the preflight test for this image, it passed.
## Version and Command Invocation
1.4.1

## Steps to Reproduce:
1) build the image refer to the [dockerfile](https://github.com/Infinidat/cinder/commit/dc044c87791fb9d7caed7658d0cdd15d4520286c#diff-e58f4ed034f19f0d4c01795b2255eb8860f9a9bf478f90d4bb18e58d832197f8)
2) run the preflight tool with the image

## Expected Result
Test name: HasModifiedFiles -should fail
Policy guide: https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.53/html-single/red_hat_openshift_software_certification_policy_guide/index#assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction
*************************
Container images must not change content provided by Red Hat packages or layers except for files that both you or the customers can change, such as configuration files.

## Actual Result
The test results showed pass
 https://connect.redhat.com/projects/5f018e64ab0698a38db07f54/overview
sha256:1aebded18e9317ab3338d8f34ba8bcc5aebe98e566a51eae6775389dda059f68 -> pass

**Comment by acornett21** [comment]
It looks to me like they are changing a file in the python library that they are installing in the image, not a file that RH provides in the base image. Or am I reading this incorrectly?

**Comment by bcrochet** [comment]
This is bigger than it looks on the surface, and will extend beyond this partner/image.

There was a disconnect in the code about what constituted a match as far as whether a file was changed or not. Because it was never actually testing for any files, it was giving a false positive (meaning, the check was passing even if it shouldn't). Once the initial bug was fixed, the code was now going in the opposite direction and giving false negatives. Too many files were being flagged when indeed they should just be ignored.

Things like /etc/shadow and /etc/passwd are expected to change, even though they are "owned" by an RPM. /var/lib/rpm/* is expected to change, given that additional RPMs could be installed.

Which gives another problem. We are using the _final_ version of the RPM db to check the files against, but we really should be using the _first_ version. 

It might make sense to narrow the scope of modified files. More like if things in /usr/{bin,lib}, or other "system" directories don't have files from RPMs modified.

**Comment by jfrancin** [comment]
This gets into the same sorts of 'interesting' problems we see in the RPM tests in RHCert. There are certain whole 'classes' of files that are expected to be modified by sysadmins (like everything in /etc), or are modified at runtime yet are supplied by RPMs (like /run/user/0/<some file path), etc. The kinds of files considered for this check need to definitely be ring-fenced. You could talk with Greg Nichols in the rhcert dev team to get his viewpoint on this.

**Comment by bcrochet** [comment]
@jfrancin That's a useful observation. Part of what I've started on this fix is to use the file flags from RPM to weed out configs and docs and such. I will reach out to Greg. Thanks for that suggestion.
