### ISSUE TITLE
preflight cannot process tests with whiteout files present in the bundle directory

### ISSUE THREAD

**Issue by yashoza19** [redhat-openshift-ecosystem/openshift-preflight#928]
## Bug Description
preflight is not able to show the errors or run tests on bundles that have whiteout files in the bundle directory.
Eg: registry.redhat.io/openshift-update-service/cincinnati-operator-bundle@sha256:2743f74cc102c059d7c1dc6698eb947cca75a3cc4230905f09703666ae7a4dbf

## Version and Command Invocation
preflight version 0.0.0 <commit: 8973da0f12304b7b6f18b9d6687639be3d0ad9b9>

## Steps to Reproduce:
(How can we reproduce this?)
1) run preflight against registry.redhat.io/openshift-update-service/cincinnati-operator-bundle@sha256:2743f74cc102c059d7c1dc6698eb947cca75a3cc4230905f09703666ae7a4dbf
``` 
preflight check operator registry.redhat.io/openshift-update-service/cincinnati-operator-bundle@sha256:2743f74cc102c059d7c1dc6698eb947cca75a3cc4230905f09703666ae7a4dbf
```

## Expected Result
Show errors in debug log.

## Actual Result
After running preflight in debug mode:
```
result log: 2023/03/22 19:29:38 error loading objs in directory: bundle manifests dir has hidden file: /bundle/manifests/.wh..wh..opq
```

cc: @acornett21

**Comment by bcrochet** [comment]
Can we get some more information about how exactly this bundle was built? It seems like an extreme edge case. This particular image has a single layer. So why the whiteout files? Are they flattening the bundle layers? 

The root cause is that crane does not handle these opaque whiteout files. But there really is no reason for these to even exist. This is technically an out-of-spec OCI image.
