### ISSUE TITLE
Is the requirement section accurate?

### ISSUE THREAD

**Issue by lucacome** [redhat-openshift-ecosystem/openshift-preflight#992]
## Requirements

For running the Preflight binary, the host or VM must have at least RHEL 8.5, CentOS 8.5 or Fedora 35 installed.

The Preflight binary currently requires that you have the following tools installed,
functional, and in your path.

| Name             | Tool cli          | Minimum version |
|----------------- |:-----------------:|----------------:|
| OperatorSDK      | `operator-sdk`    |         v1.28.0 |

The requirement section that states that RHEL, CentOS or Fedora are required to run the binary and that the `operator-sdk` needs to be installed.
It doesn't seem accurate to me as I've been able to run the binary on Ubuntu or macOS without problems, also without the `operator-sdk` installed.

I just wanted to figure out if I'm doing something wrong or if the section can be deleted.

**Comment by acornett21** [comment]
@lucacome `operator-sdk` is required for `check operator` where we call `operator-sdk scorecard` against the operator bundle image. I think you are using the `preflight` binary to run `check container`, then using our hosted pipeline to certify/validate the operator `bundle` and aren't doing any iterative executions of preflight against the operator and a cluster. Please correct my last point if I'm mistaken and you are also running `preflight check operator`

**Comment by lucacome** [comment]
Thanks @acornett21 you're correct, we're only using `check container`. So both requirements are only for `check operator`?

**Comment by acornett21** [comment]
@lucacome I missed the part of the question for the `host system os`, in reality the host system can be any OS that can run a binary we distribute. The dependency section, was alot longer when `preflight`was first written, but now we can rely on libraries instead of the host system having `x,y,z` dependency installed for our checks/policies. So, we wanted the host OS to be known to come with those dependencies, but now that we really only have the one and it's for `check operator` this documentation can be cleaned up.

**Comment by acornett21** [comment]
@lucacome I think this issue was addressed in the comment above, so I am going to close this issue. Feel free to re-open if you feel this was not resolved.
